<?php
/**
 * @var \Base\WholesaleRequestForm\Block\Form $block
 */
?>
<div class="wholesale_request-container">
    <?php if ($block->isRequestSent()): ?>
        <p class="request-status"><?php echo $block->escapeHtml(__($block->requestStatusMessage())) ?></p>
    <?php else: ?>
        <form id="my-form" method="POST" data-mage-init='{"validation": {}}'>
            <div class="form-group">
                <label for="inn"><?php echo $block->escapeHtml(__('INN:')); ?></label>
                <input type="number" class="form-control" id="inn" name="inn" data-validate="{'required':true}">
            </div>
            <div class="form-group">
                <label for="id-image"><?php echo $block->escapeHtml(__('ID Image (optional):')); ?></label>
                <input type="file" class="form-control" id="id-image" name="id-image" accept="image/*">
            </div>
            <div class="form-group">
                <label for="region"><?php echo $block->escapeHtml(__('Region:')); ?></label>
                <select class="form-control" id="region" name="region" data-validate="{'required':true}">
                    <?php foreach ($block->statesCollection() as $region): ?>
                        <option value="<?php echo $block->escapeHtml($region['state']); ?>">
                            <?php echo $block->escapeHtml(__($region['state'])); ?>
                        </option>
                    <?php endforeach; ?>
                </select>
            </div>
            <div class="form-group">
                <label for="city"><?php echo $block->escapeHtml(__('City:')); ?></label>
                <input type="text" class="form-control" id="city" name="city" data-validate="{'required':true}">
            </div>
            <div class="form-group">
                <label for="company"><?php echo $block->escapeHtml(__('Company:')); ?></label>
                <input type="text" class="form-control" id="company" name="company" data-validate="{'required':true}">
            </div>
            <div class="form-group">
                <label for="text"><?php echo $block->escapeHtml(__('Text:')); ?></label>
                <textarea class="form-control" id="text" name="text" rows="5" data-validate="{'required':true}"
                          placeholder="<?php echo $block->escapeHtml(__('Describe please, why you need a wholesale group')); ?>"></textarea>
            </div>
            <input type="submit" id="submit-btn" class="btn btn-primary wholesale_btn_submit" name="submit-btn"
                   value="<?php echo $block->escapeHtml(__('Submit')); ?>">
        </form>
        <script type="text/x-magento-init">
    {
        "*": {
            "Base_WholesaleRequestForm/js/send-request" : {}
        }
    }

        </script>
    <?php endif; ?>
</div>
