<?php
/**
 * @var \Base\WholesaleRequestForm\Block\Wholesalers\Index $block
 */
?>

<div class="wholesalers-container">
    <div class="wholesalers-region">
        <h3 class="region-title"><?php echo $block->escapeHtml(__("Wholesalers by region:")) ?></h3>
        <ul class="region-list">
            <li class="region-item active" data-state="0">
                <p class="region-name">
                    <?php echo $block->escapeHtml(__('All regions')) ?>
                </p>
            </li>
            <?php foreach ($block->getRegionCollection() as $region): ?>
                <li class="region-item" data-state="<?php echo $region['state']; ?>">
                    <p class="region-name">
                        <?php echo $block->escapeHtml(__($region['state'])) ?>
                    </p>
                </li>
            <?php endforeach; ?>
        </ul>
    </div>
    <div class="wholesalers">
        <?php if ($block->getWholesalersCollection()): ?>
        <div class="custom-google_maps-wholesalers" >
            <p class="custom-google_maps-title-wholesalers">Wholesalers in map:</p>
            <div id="map"></div>
        </div>
        <?php endif; ?>
        <ul class="wholesalers-list">
            <?php if ($block->getWholesalersCollection()): ?>
                <?php foreach ($block->getWholesalersCollection() as $wholesalers): ?>
                    <li class="wholesalers-item">
                        <?php if ($wholesalers['image'] != "null"): ?>
                            <img class="company-image" width="100" height="100"
                                 alt="image"
                                 src="<?php echo $block->getBaseUrlForImage() . $wholesalers['image'] ?>"/>
                        <?php else: ?>
                            <img class="company-image" width="100" height="100"
                                 alt="image"
                                 src="<?php echo $block->getBaseUrlForImage() . "base/wholesalerequestform/default/default-image.png" ?>"/>
                        <?php endif; ?>
                        <p class="wholesalers-company">
                            <?php echo $block->escapeHtml(__($wholesalers['company'])) ?>
                        </p>
                        <p class="wholesalers-city">
                            <?php echo $block->escapeHtml(__($wholesalers['city'])) ?>
                        </p>
                        <p class="wholesalers-name">
                            <?php echo $block->escapeHtml(__($wholesalers['name'])) ?>
                        </p>
                        <p class="wholesalers-email">
                            <?php echo $block->escapeHtml(__($wholesalers['email'])) ?>
                        </p>
                        <p hidden="hidden" class="latitude"><?php echo $block->escapeHtml($wholesalers['location_latitude']) ?></p>
                        <p hidden="hidden" class="longitude"><?php echo $block->escapeHtml($wholesalers['location_longitude']) ?></p>
                    </li>
                <?php endforeach; ?>
            <?php endif; ?>
        </ul>
    </div>
</div>

<script type="text/x-magento-init">
    {
        "*": {
            "Base_WholesaleRequestForm/js/show-wholesalers" : {}
        }
    }
</script>
<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBsITeocaRiIlka_inElQdA6Gk3H5nk2aw&callback=initMap&v=weekly" async defer></script>
<script>
    async function initMap() {

            const { Map } = await google.maps.importLibrary("maps");

            const map = new Map(document.getElementById("map"), {
                zoom: 5,
                center: { lat: 49, lng: 32 },
                mapId: "DEMO_MAP_ID",
            });

            const wholesalersItems = document.getElementsByClassName("wholesalers-item");
            const company = document.querySelector(".wholesalers-company")

            if (company != null) {
                for (let i = 0; i < wholesalersItems.length; i++) {
                    const wholesalersItem = wholesalersItems[i];
                    const latitude = parseFloat(wholesalersItem.querySelector(".latitude").textContent);
                    const longitude = parseFloat(wholesalersItem.querySelector(".longitude").textContent);
                    const companyName = wholesalersItem.querySelector(".wholesalers-company").textContent

                    const position = {lat: latitude, lng: longitude};

                    const marker = new google.maps.Marker({
                        map: map,
                        position: position,
                        label: {
                            fontWeight: 'bold',
                            text: companyName,
                        },
                    });
                }
            }
    }

    window.initMap = initMap;
</script>
